### ISSUE TITLE
Add tests/leap/nodeos_trust_evm_test.py to CI

### ISSUE THREAD

**Issue by kj4ezj** [eosnetworkfoundation/eos-evm-contract#332]
From [this comment](https://github.com/eosnetworkfoundation/TrustEVM/issues/242#issuecomment-1416140916) in [issue 242](https://github.com/eosnetworkfoundation/TrustEVM/issues/242), @heifner would like the `tests/leap/nodeos_trust_evm_test.py` test to be included in the CI system. This test is not as straightforward as invoking the Python file. It requires Leap to be available and running, among other conditions defined in a comment at the top of the test source code. This is beyond the scope of [issue 242](https://github.com/eosnetworkfoundation/TrustEVM/issues/242), so I have broken it out into a separate issue. It may also require changes to Leap, I am not sure where that discussion landed.

**Comment by heifner** [comment]
Resolved by https://github.com/eosnetworkfoundation/eos-evm-node/pull/17
