### ISSUE TITLE
Use silkworm submodule library when building evm_runtime contract unit_tests 

### ISSUE THREAD

**Issue by elmato** [eosnetworkfoundation/eos-evm-contract#605]
First, leap should be able to be built using c++20.
https://github.com/AntelopeIO/leap/issues/1079

**Comment by stephenpdeos** [comment]
We would like to use the copy of silkworm we use in building our contracts for building our tests as well. (Right now we use a separate copy because of a limitation of not being able to use C++20 in libtester, but that limitation is removed with the libtester pulled in from the Leap 5 dependency.)
