### ISSUE TITLE
Update unit test coverage to support a different gas token than EOS

### ISSUE THREAD

**Issue by stephenpdeos** [eosnetworkfoundation/eos-evm-contract#700]
Update the unit tests to support a different gas token than EOS

**Comment by stephenpdeos** [comment]
Move the TOKEN_ACCOUNT_NAME constant to cmake
Move the token_symbol constant to cmake
Move the token_account_name constant to cmake
Make all of these configurable in cmake
In the tester, clean up all references to eosio.token
In the tester, clean up all references to native_symbol

**Comment by elmato** [comment]
Superseded by https://github.com/eosnetworkfoundation/eos-evm-contract/issues/708
